# coding: utf-8
import pandas as pd
import numpy as np
from sklearn.metrics import log_loss, roc_auc_score
from sklearn.model_selection import train_test_split
from tensorflow import keras
from sklearn.metrics import classification_report

from deepctr.feature_column import SparseFeat, DenseFeat, get_feature_names
from deepctr.models import DeepFM


train_data = pd.read_csv('../data/cleaned_train.csv')

train_data.info()

ind_cd_cols = []
for col in train_data.columns:
    if col.endswith('ind') or col.endswith('cd'):
        ind_cd_cols.append(col)
ind_cd_cols = list(set(ind_cd_cols))


sparse_features = ind_cd_cols + ['cons_cmys', 'cons_hhcomp', 'cons_homstat',
                                           'cons_n2029_y', 'cons_n65p_y', 'cons_online_buyer', 'cons_ret_y', 'cons_retail_buyer', 'cons_veteran_y',
                                           'hedis_dia_eye', 'hedis_dia_hba1c_ge9', 'hedis_dia_hba1c_test',
                                           'hedis_dia_ldc_c_control', 'hedis_dia_ldc_c_screen', 'hedis_dia_ma_nephr', 'hlth_pgm_slvrsnkr_par_status',
                                           'mabh_seg', 'rucc_category', 'cons_hcaccprf']

sparse_features = list(set(sparse_features))

field_info = {'betos_d1c_ind': 'Medical Claims Features',
             'betos_d1d_ind': 'Medical Claims Features',
             'betos_m1b_ind': 'Medical Claims Features',
             'betos_m2c_ind': 'Medical Claims Features',
             'betos_m5b_ind': 'Medical Claims Features',
             'betos_m5c_ind': 'Medical Claims Features',
             'betos_m5d_ind': 'Medical Claims Features',
             'betos_o1a_ind': 'Medical Claims Features',
             'betos_o1b_ind': 'Medical Claims Features',
             'betos_o1e_ind': 'Medical Claims Features',
             'betos_o1g_ind': 'Medical Claims Features',
             'betos_t1a_ind': 'Medical Claims Features',
             'betos_t1b_ind': 'Medical Claims Features',
             'betos_t1e_ind': 'Medical Claims Features',
             'betos_t1h_ind': 'Medical Claims Features',
             'betos_t2a_ind': 'Medical Claims Features',
             'betos_y2_ind': 'Medical Claims Features',
             'bh_adtp_ind': 'Condition Related Features',
             'bh_aoth_ind': 'Condition Related Features',
             'bh_bipr_ind': 'Condition Related Features',
             'bh_cdal_ind': 'Condition Related Features',
             'bh_cdsb_ind': 'Condition Related Features',
             'bh_cdto_ind': 'Condition Related Features',
             'bh_dema_ind': 'Condition Related Features',
             'ccsp_014_ind': 'Medical Claims Features',
             'ccsp_020_ind': 'Medical Claims Features',
             'ccsp_021_ind': 'Medical Claims Features',
             'ccsp_060_ind': 'Medical Claims Features',
             'ccsp_062_ind': 'Medical Claims Features',
             'ccsp_080_ind': 'Medical Claims Features',
             'ccsp_107_ind': 'Medical Claims Features',
             'ccsp_125_ind': 'Medical Claims Features',
             'ccsp_130_ind': 'Medical Claims Features',
             'ccsp_163_ind': 'Medical Claims Features',
             'ccsp_169_ind': 'Medical Claims Features',
             'ccsp_204_ind': 'Medical Claims Features',
             'ccsp_205_ind': 'Medical Claims Features',
             'ccsp_212_ind': 'Medical Claims Features',
             'ccsp_220_ind': 'Medical Claims Features',
             'ccsp_228_ind': 'Medical Claims Features',
             'ccsp_236_ind': 'Medical Claims Features',
             'ccsp_239_ind': 'Medical Claims Features',
             'ccsp_242_ind': 'Medical Claims Features',
             'cms_disabled_ind': 'CMS Features',
             'cms_dual_eligible_ind': 'CMS Features',
             'cms_hospice_ind': 'CMS Features',
             'cms_low_income_ind': 'CMS Features',
             'cms_ra_factor_type_cd': 'CMS Features',
             'cmsd2_can_unc_neo/plycyth/myelo_ind': 'CMS Features',
             'cmsd2_eye_blindness_ind': 'CMS Features',
             'cmsd2_gus_m_genital_ind': 'CMS Features',
             'cmsd2_men_mad_ind': 'CMS Features',
             'cmsd2_men_men_substance_ind': 'CMS Features',
             'cmsd2_mus_polyarthropath_ind': 'CMS Features',
             'cmsd2_mus_spondylopath_ind': 'CMS Features',
             'cmsd2_skn_radiation_ind': 'CMS Features',
             'cmsd2_sns_general_ind': 'CMS Features',
             'cnty_cd': 'Demographics',
             'cons_cmys': 'Demographics',
             'cons_hcaccprf': 'Demographics',
             'cons_hhcomp': 'Demographics',
             'cons_homstat': 'Demographics',
             'cons_n2029_y': 'Demographics',
             'cons_n65p_y': 'Demographics',
             'cons_online_buyer': 'Demographics',
             'cons_ret_y': 'Demographics',
             'cons_retail_buyer': 'Demographics',
             'cons_veteran_y': 'Demographics',
             'hedis_dia_eye': 'Condition Related Features',
             'hedis_dia_hba1c_ge9': 'Condition Related Features',
             'hedis_dia_hba1c_test': 'Condition Related Features',
             'hedis_dia_ldc_c_control': 'Condition Related Features',
             'hedis_dia_ldc_c_screen': 'Condition Related Features',
             'hedis_dia_ma_nephr': 'Condition Related Features',
             'hlth_pgm_slvrsnkr_par_status': 'Other features',
             'lab_abn_result_ind': 'Lab Claims Features',
             'lab_bnp_abn_result_ind': 'Lab Claims Features',
             'lab_bun_abn_result_ind': 'Lab Claims Features',
             'lab_cholesterol_abn_result_ind': 'Lab Claims Features',
             'lab_creatinine_abn_result_ind': 'Lab Claims Features',
             'lab_egfr_abn_result_ind': 'Lab Claims Features',
             'lab_hemoglobin_abn_result_ind': 'Lab Claims Features',
             'lang_spoken_cd': 'Demographics',
             'mabh_seg': 'Other features',
             'phy_em_pe_ind': 'Condition Related Features',
             'phy_em_pi_ind': 'Condition Related Features',
             'phy_em_px_ind': 'Condition Related Features',
             'prov_fb_ind': 'Other features',
             'prov_pcp_ind': 'Other features',
             'prov_sp_ind': 'Other features',
             'prov_spec_addiction_all_ind': 'Other features',
             'prov_spec_ambulance_ind': 'Other features',
             'prov_spec_bh_psychiatric_ind': 'Other features',
             'prov_spec_chiropractic_ind': 'Other features',
             'prov_spec_home_health_ind': 'Other features',
             'prov_spec_med_supply_ind': 'Other features',
             'prov_spec_nurse_phy_assist_ind': 'Other features',
             'prov_spec_pain_mgmt_ind': 'Other features',
             'prov_spec_phy_general_ind': 'Other features',
             'prov_spec_phy_geriatric_ind': 'Other features',
             'rev_cms_ambul_ind': 'Condition Related Features',
             'rev_cms_clinic_ind': 'Condition Related Features',
             'rev_cms_er_ind': 'Condition Related Features',
             'rev_cms_icu_ind': 'Condition Related Features',
             'rev_cms_lab_ind': 'Condition Related Features',
             'rev_cms_phar_ind': 'Condition Related Features',
             'rucc_category': 'Demographics',
             'rx_bh_ind': 'Pharmacy Claims Features',
             'rx_branded_ind': 'Pharmacy Claims Features',
             'rx_generic_ind': 'Pharmacy Claims Features',
             'rx_gpi2_01_ind': 'Pharmacy Claims Features',
             'rx_gpi2_02_ind': 'Pharmacy Claims Features',
             'rx_gpi2_03_ind': 'Pharmacy Claims Features',
             'rx_gpi2_04_ind': 'Pharmacy Claims Features',
             'rx_gpi2_05_ind': 'Pharmacy Claims Features',
             'rx_gpi2_07_ind': 'Pharmacy Claims Features',
             'rx_gpi2_09_ind': 'Pharmacy Claims Features',
             'rx_gpi2_11_ind': 'Pharmacy Claims Features',
             'rx_gpi2_12_ind': 'Pharmacy Claims Features',
             'rx_gpi2_13_ind': 'Pharmacy Claims Features',
             'rx_gpi2_15_ind': 'Pharmacy Claims Features',
             'rx_gpi2_16_ind': 'Pharmacy Claims Features',
             'rx_gpi2_17_ind': 'Pharmacy Claims Features',
             'rx_gpi2_18_ind': 'Pharmacy Claims Features',
             'rx_gpi2_21_ind': 'Pharmacy Claims Features',
             'rx_gpi2_22_ind': 'Pharmacy Claims Features',
             'rx_gpi2_23_ind': 'Pharmacy Claims Features',
             'rx_gpi2_24_ind': 'Pharmacy Claims Features',
             'rx_gpi2_25_ind': 'Pharmacy Claims Features',
             'rx_gpi2_26_ind': 'Pharmacy Claims Features',
             'rx_gpi2_27_ind': 'Pharmacy Claims Features',
             'rx_gpi2_28_ind': 'Pharmacy Claims Features',
             'rx_gpi2_30_ind': 'Pharmacy Claims Features',
             'rx_gpi2_31_ind': 'Pharmacy Claims Features',
             'rx_gpi2_32_ind': 'Pharmacy Claims Features',
             'rx_gpi2_33_ind': 'Pharmacy Claims Features',
             'rx_gpi2_34_ind': 'Pharmacy Claims Features',
             'rx_gpi2_35_ind': 'Pharmacy Claims Features',
             'rx_gpi2_36_ind': 'Pharmacy Claims Features',
             'rx_gpi2_37_ind': 'Pharmacy Claims Features',
             'rx_gpi2_38_ind': 'Pharmacy Claims Features',
             'rx_gpi2_39_ind': 'Pharmacy Claims Features',
             'rx_gpi2_40_ind': 'Pharmacy Claims Features',
             'rx_gpi2_41_ind': 'Pharmacy Claims Features',
             'rx_gpi2_42_ind': 'Pharmacy Claims Features',
             'rx_gpi2_43_ind': 'Pharmacy Claims Features',
             'rx_gpi2_44_ind': 'Pharmacy Claims Features',
             'rx_gpi2_46_ind': 'Pharmacy Claims Features',
             'rx_gpi2_47_ind': 'Pharmacy Claims Features',
             'rx_gpi2_48_ind': 'Pharmacy Claims Features',
             'rx_gpi2_49_ind': 'Pharmacy Claims Features',
             'rx_gpi2_50_ind': 'Pharmacy Claims Features',
             'rx_gpi2_51_ind': 'Pharmacy Claims Features',
             'rx_gpi2_52_ind': 'Pharmacy Claims Features',
             'rx_gpi2_53_ind': 'Pharmacy Claims Features',
             'rx_gpi2_54_ind': 'Pharmacy Claims Features',
             'rx_gpi2_55_ind': 'Pharmacy Claims Features',
             'rx_gpi2_56_ind': 'Pharmacy Claims Features',
             'rx_gpi2_57_ind': 'Pharmacy Claims Features',
             'rx_gpi2_58_ind': 'Pharmacy Claims Features',
             'rx_gpi2_59_ind': 'Pharmacy Claims Features',
             'rx_gpi2_60_ind': 'Pharmacy Claims Features',
             'rx_gpi2_61_ind': 'Pharmacy Claims Features',
             'rx_gpi2_62_ind': 'Pharmacy Claims Features',
             'rx_gpi2_64_ind': 'Pharmacy Claims Features',
             'rx_gpi2_65_ind': 'Pharmacy Claims Features',
             'rx_gpi2_66_ind': 'Pharmacy Claims Features',
             'rx_gpi2_67_ind': 'Pharmacy Claims Features',
             'rx_gpi2_68_ind': 'Pharmacy Claims Features',
             'rx_gpi2_72_ind': 'Pharmacy Claims Features',
             'rx_gpi2_73_ind': 'Pharmacy Claims Features',
             'rx_gpi2_74_ind': 'Pharmacy Claims Features',
             'rx_gpi2_75_ind': 'Pharmacy Claims Features',
             'rx_gpi2_77_ind': 'Pharmacy Claims Features',
             'rx_gpi2_78_ind': 'Pharmacy Claims Features',
             'rx_gpi2_79_ind': 'Pharmacy Claims Features',
             'rx_gpi2_82_ind': 'Pharmacy Claims Features',
             'rx_gpi2_83_ind': 'Pharmacy Claims Features',
             'rx_gpi2_85_ind': 'Pharmacy Claims Features',
             'rx_gpi2_86_ind': 'Pharmacy Claims Features',
             'rx_gpi2_87_ind': 'Pharmacy Claims Features',
             'rx_gpi2_88_ind': 'Pharmacy Claims Features',
             'rx_gpi2_89_ind': 'Pharmacy Claims Features',
             'rx_gpi2_90_ind': 'Pharmacy Claims Features',
             'rx_gpi2_93_ind': 'Pharmacy Claims Features',
             'rx_gpi2_94_ind': 'Pharmacy Claims Features',
             'rx_gpi2_97_ind': 'Pharmacy Claims Features',
             'rx_gpi2_99_ind': 'Pharmacy Claims Features',
             'rx_mail_ind': 'Pharmacy Claims Features',
             'rx_maint_ind': 'Pharmacy Claims Features',
             'rx_otc_ind': 'Pharmacy Claims Features',
             'sex_cd': 'Demographics',
             'smoker_current_ind': 'Demographics',
             'smoker_former_ind': 'Demographics',
             'src_platform_cd': 'Other features',
             'state_cd': 'Demographics',
             'submcc_ano_cns_ind': 'Condition Related Features',
             'submcc_ano_dig_ind': 'Condition Related Features',
             'submcc_ano_gu_ind': 'Condition Related Features',
             'submcc_ano_hrt_ind': 'Condition Related Features',
             'submcc_ano_mus_ind': 'Condition Related Features',
             'submcc_ano_othr_ind': 'Condition Related Features',
             'submcc_ben_ner_ind': 'Condition Related Features',
             'submcc_ben_othr_ind': 'Condition Related Features',
             'submcc_ben_unk_ind': 'Condition Related Features',
             'submcc_bld_anem_ind': 'Condition Related Features',
             'submcc_bld_othr_ind': 'Condition Related Features',
             'submcc_brn_othr_ind': 'Condition Related Features',
             'submcc_cad_ang_ind': 'Condition Related Features',
             'submcc_cad_ashd_ind': 'Condition Related Features',
             'submcc_cad_cabg_ind': 'Condition Related Features',
             'submcc_cad_isch_ind': 'Condition Related Features',
             'submcc_cad_mi_ind': 'Condition Related Features',
             'submcc_cad_ptca_ind': 'Condition Related Features',
             'submcc_can_brst_ind': 'Condition Related Features',
             'submcc_can_dig_ind': 'Condition Related Features',
             'submcc_can_end_ind': 'Condition Related Features',
             'submcc_can_gu_ind': 'Condition Related Features',
             'submcc_can_h/n_ind': 'Condition Related Features',
             'submcc_can_h/o_ind': 'Condition Related Features',
             'submcc_can_leuk_ind': 'Condition Related Features',
             'submcc_can_lymp_ind': 'Condition Related Features',
             'submcc_can_ner_ind': 'Condition Related Features',
             'submcc_can_othr_ind': 'Condition Related Features',
             'submcc_can_res_ind': 'Condition Related Features',
             'submcc_can_sec_ind': 'Condition Related Features',
             'submcc_can_skn_ind': 'Condition Related Features',
             'submcc_cer_hem_ind': 'Condition Related Features',
             'submcc_cer_occ_ind': 'Condition Related Features',
             'submcc_cer_seq_ind': 'Condition Related Features',
             'submcc_cer_tia_ind': 'Condition Related Features',
             'submcc_cir_anur_ind': 'Condition Related Features',
             'submcc_cir_art_ind': 'Condition Related Features',
             'submcc_cir_hbp_ind': 'Condition Related Features',
             'submcc_cir_othr_ind': 'Condition Related Features',
             'submcc_dia_eye_ind': 'Condition Related Features',
             'submcc_dia_nep_ind': 'Condition Related Features',
             'submcc_dia_neu_ind': 'Condition Related Features',
             'submcc_dia_othr_ind': 'Condition Related Features',
             'submcc_dia_pvd_ind': 'Condition Related Features',
             'submcc_dig_lgi_ind': 'Condition Related Features',
             'submcc_dig_liv_ind': 'Condition Related Features',
             'submcc_dig_othr_ind': 'Condition Related Features',
             'submcc_dig_p/b_ind': 'Condition Related Features',
             'submcc_dig_ugi_ind': 'Condition Related Features',
             'submcc_end_gld_ind': 'Condition Related Features',
             'submcc_end_meta_ind': 'Condition Related Features',
             'submcc_end_nutr_ind': 'Condition Related Features',
             'submcc_end_othr_ind': 'Condition Related Features',
             'submcc_end_thy_ind': 'Condition Related Features',
             'submcc_gus_brst_ind': 'Condition Related Features',
             'submcc_gus_fem_ind': 'Condition Related Features',
             'submcc_gus_kub_ind': 'Condition Related Features',
             'submcc_gus_male_ind': 'Condition Related Features',
             'submcc_gus_othr_ind': 'Condition Related Features',
             'submcc_hdz_arrh_ind': 'Condition Related Features',
             'submcc_hdz_it_is_ind': 'Condition Related Features',
             'submcc_hdz_myop_ind': 'Condition Related Features',
             'submcc_hdz_othr_ind': 'Condition Related Features',
             'submcc_hdz_valv_ind': 'Condition Related Features',
             'submcc_hiv_othr_ind': 'Condition Related Features',
             'submcc_inf_cand_ind': 'Condition Related Features',
             'submcc_inf_myco_ind': 'Condition Related Features',
             'submcc_inf_othr_ind': 'Condition Related Features',
             'submcc_inf_sep_ind': 'Condition Related Features',
             'submcc_inj_comp_ind': 'Condition Related Features',
             'submcc_inj_drug_ind': 'Condition Related Features',
             'submcc_inj_org_ind': 'Condition Related Features',
             'submcc_inj_othr_ind': 'Condition Related Features',
             'submcc_men_abus_ind': 'Condition Related Features',
             'submcc_men_alco_ind': 'Condition Related Features',
             'submcc_men_depr_ind': 'Condition Related Features',
             'submcc_men_othr_ind': 'Condition Related Features',
             'submcc_men_schz_ind': 'Condition Related Features',
             'submcc_mus_arth_ind': 'Condition Related Features',
             'submcc_mus_atrp_ind': 'Condition Related Features',
             'submcc_mus_back_ind': 'Condition Related Features',
             'submcc_mus_form_ind': 'Condition Related Features',
             'submcc_mus_inf_ind': 'Condition Related Features',
             'submcc_mus_jnt_ind': 'Condition Related Features',
             'submcc_mus_oste_ind': 'Condition Related Features',
             'submcc_mus_othr_ind': 'Condition Related Features',
             'submcc_mus_soft_ind': 'Condition Related Features',
             'submcc_ner_deg_ind': 'Condition Related Features',
             'submcc_ner_epil_ind': 'Condition Related Features',
             'submcc_ner_infl_ind': 'Condition Related Features',
             'submcc_ner_migr_ind': 'Condition Related Features',
             'submcc_ner_othr_ind': 'Condition Related Features',
             'submcc_pre_care_ind': 'Condition Related Features',
             'submcc_pre_com_ind': 'Condition Related Features',
             'submcc_rar_cid_ind': 'Condition Related Features',
             'submcc_rar_hem_ind': 'Condition Related Features',
             'submcc_rar_lup_ind': 'Condition Related Features',
             'submcc_rar_ms_ind': 'Condition Related Features',
             'submcc_rar_par_ind': 'Condition Related Features',
             'submcc_rar_ra_ind': 'Condition Related Features',
             'submcc_rar_scl_ind': 'Condition Related Features',
             'submcc_res_alg_ind': 'Condition Related Features',
             'submcc_res_asth_ind': 'Condition Related Features',
             'submcc_res_copd_ind': 'Condition Related Features',
             'submcc_res_fail_ind': 'Condition Related Features',
             'submcc_res_inf_ind': 'Condition Related Features',
             'submcc_res_othr_ind': 'Condition Related Features',
             'submcc_rsk_chol_ind': 'Condition Related Features',
             'submcc_rsk_coag_ind': 'Condition Related Features',
             'submcc_rsk_fh/ho_ind': 'Condition Related Features',
             'submcc_rsk_glu_ind': 'Condition Related Features',
             'submcc_rsk_obe_ind': 'Condition Related Features',
             'submcc_rsk_smok_ind': 'Condition Related Features',
             'submcc_rsk_synx_ind': 'Condition Related Features',
             'submcc_skn_inf_ind': 'Condition Related Features',
             'submcc_skn_othr_ind': 'Condition Related Features',
             'submcc_sns_abd_ind': 'Condition Related Features',
             'submcc_sns_chst_ind': 'Condition Related Features',
             'submcc_sns_coma_ind': 'Condition Related Features',
             'submcc_sns_cons_ind': 'Condition Related Features',
             'submcc_sns_dth_ind': 'Condition Related Features',
             'submcc_sns_othr_ind': 'Condition Related Features',
             'submcc_sor_ear_ind': 'Condition Related Features',
             'submcc_sor_eye_ind': 'Condition Related Features',
             'submcc_trm_brn_ind': 'Condition Related Features',
             'submcc_trm_f/n_ind': 'Condition Related Features',
             'submcc_trm_hip_ind': 'Condition Related Features',
             'submcc_trm_prly_ind': 'Condition Related Features',
             'submcc_trm_skul_ind': 'Condition Related Features',
             'submcc_trm_spfx_ind': 'Condition Related Features',
             'submcc_trm_spnj_ind': 'Condition Related Features',
             'submcc_vco_care_ind': 'Condition Related Features',
             'submcc_vco_end_ind': 'Condition Related Features',
             'submcc_vco_exam_ind': 'Condition Related Features',
             'submcc_vco_othr_ind': 'Condition Related Features',
             'submcc_vco_vac_ind': 'Condition Related Features',
             'zip_cd': 'Demographics'}

size_dict = {'Medical Claims Features': 2,
             'Condition Related Features':2,
             'Lab Claims Features':2,
             'Pharmacy Claims Features':2,
             'CMS Features':2,
             'Demographics':16,
             'Other features':16
            }

dense_features = set(train_data.columns) - set(sparse_features) - set(['transportation_issues', 'person_id_syn'])
dense_features = list(dense_features)

target = ['transportation_issues']

fixlen_feature_columns = [SparseFeat(feat, vocabulary_size=train_data[feat].nunique(), embedding_dim=size_dict[field_info[feat]], dtype='int32', group_name=field_info[feat]) for feat in sparse_features] + [DenseFeat(feat, 1,) for feat in dense_features]

dnn_feature_columns = fixlen_feature_columns
linear_feature_columns = fixlen_feature_columns

feature_names = get_feature_names(linear_feature_columns + dnn_feature_columns)

train, test = train_test_split(train_data, test_size=0.2, random_state=2020)
train_model_input = {name:train[name] for name in feature_names}
test_model_input = {name:test[name] for name in feature_names}

model = DeepFM(linear_feature_columns, dnn_feature_columns, task='binary', dnn_hidden_units=(2, 256), dnn_dropout=0.0)
opt = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="binary_crossentropy", metrics=['binary_crossentropy'], optimizer=opt)

history = model.fit(train_model_input, train[target].values, batch_size=64, epochs=10, verbose=1, validation_split=0.2, class_weight={0:1, 1:3})
pred_ans = model.predict(test_model_input, batch_size=64)
print("test LogLoss", round(log_loss(test[target].values, pred_ans), 4))
print("test AUC", round(roc_auc_score(test[target].values, pred_ans), 4))

ans = pd.Series(pred_ans.reshape((-1,)))
ans[ans>=0.5] = 1
ans[ans<0.5] = 0

pd.Series(test[target].transportation_issues).value_counts()

ans.value_counts()

print(classification_report(test[target], ans))

model.summary()





